# Generated by Django 3.2.5 on 2021-08-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='actualizado_el',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='creado_el',
            new_name='creado',
        ),
    ]
